@startuml
'https://plantuml.com/activity-diagram-beta

start

if (Zugriff auf Server?) then (Ja)
    if (Bidirektional benötigt?) then (Ja)
        if (Media Streams nötig?) then (Ja)
            :WebRTC;
            stop
        else (Nein)
            if (Viel Client->Server Kommunikation?) then (Ja)
                if (Neuestes nötig?) then (Ja)
                    :WebTransport;
                    stop
                else (Nein)
                    :WebSockets;
                    stop
                endif
            else (Nein)
                :Server-Sent Events + POST;
                stop
            endif
        endif
    else (Nein)
        :Server-Sent Events;
        stop
    endif
else (Nein)
    :Short Polling;
    stop
endif

@enduml
