# fly.toml app configuration file generated for mi-web-technologien-real-time-workshop-backend on 2024-05-05T15:40:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mi-web-technologien-real-time-workshop-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080

[[vm]]
  size = 'shared-cpu-1x'
